"""GitHub Action template generator.

Generates GitHub Action workflow YAML for automated
cngx enforcement in CI/CD pipelines.
"""

from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger("cngx.enforcement.github_action")


class GitHubActionGenerator:
    """Generate GitHub Action workflow configurations."""

    @staticmethod
    def generate(
        python_version: str = "3.11",
        model: str = "gemini-flash-latest",
        provider: str = "gemini",
        contract_path: str = "contracts/",
        api_key_secret: str = "GOOGLE_API_KEY",
        drift_threshold: float = 0.3,
        accuracy_threshold: float = 0.8,
        stability_threshold: float = 0.7,
        run_benchmark: bool = False,
        run_robustness: bool = False,
        run_consensus: bool = False,
        on_push: bool = True,
        on_pull_request: bool = True,
        branches: list[str] | None = None,
        additional_env: dict[str, str] | None = None,
    ) -> str:
        """Generate GitHub Action workflow YAML."""
        branches = branches or ["main", "develop"]
        branch_list = "\n".join(f"        - {b}" for b in branches)

        trigger_push = ""
        if on_push:
            trigger_push = f"""
  push:
    branches:
{branch_list}"""

        trigger_pr = ""
        if on_pull_request:
            trigger_pr = f"""
  pull_request:
    branches:
{branch_list}"""

        env_vars = f"""
    env:
      {api_key_secret}: ${{{{ secrets.{api_key_secret} }}}}
      CNGX_MODEL: {model}
      CNGX_PROVIDER: {provider}"""

        if additional_env:
            for key, value in additional_env.items():
                env_vars += f"\n      {key}: {value}"

        benchmark_step = ""
        if run_benchmark:
            benchmark_step = f"""
      - name: Run Benchmark Suite
        run: |
          cngx benchmark run \\
            --format builtin_math \\
            --model $CNGX_MODEL \\
            --threshold {accuracy_threshold}
        continue-on-error: false"""

        robustness_step = ""
        if run_robustness:
            robustness_step = f"""
      - name: Run Robustness Tests
        run: |
          cngx robustness test \\
            --model $CNGX_MODEL \\
            --threshold {stability_threshold} \\
            --perturbations 5
        continue-on-error: false"""

        consensus_step = ""
        if run_consensus:
            consensus_step = """
      - name: Run Consensus Validation
        run: |
          cngx consensus validate \\
            --models "$CNGX_MODEL" \\
            --min-agreement 0.7
        continue-on-error: false"""

        yaml = f"""# cngx Behavioral Contract Enforcement Gate
# Generated by cngx
# https://github.com/your-org/cngx

name: cngx Enforcement Gate

on:{trigger_push}{trigger_pr}
  workflow_dispatch:
    inputs:
      mode:
        description: 'Enforcement mode (enforce/advisory)'
        required: false
        default: 'enforce'

permissions:
  contents: read
  pull-requests: write

jobs:
  cngx-gate:
    name: cngx Behavioral Contract Enforcement
    runs-on: ubuntu-latest
    timeout-minutes: 15
{env_vars}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python {python_version}
        uses: actions/setup-python@v5
        with:
          python-version: '{python_version}'
          cache: 'pip'

      - name: Install cngx
        run: |
          pip install --upgrade pip
          pip install cngx[{provider}]

      - name: Validate Contracts
        run: |
          cngx gate ci "CI regression check" \\
            -c {contract_path}math_correctness.yaml \\
            --model $CNGX_MODEL \\
            --adapter mock
        continue-on-error: false
{benchmark_step}
{robustness_step}
{consensus_step}
      - name: Comment PR with Results
        if: github.event_name == 'pull_request' && always()
        uses: actions/github-script@v7
        with:
          script: |
            const status = '${{{{ job.status }}}}' === 'success' ? '✅ PASSED' : '❌ FAILED';
            await github.rest.issues.createComment({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## cngx Enforcement Gate ${{status}}\\n\\n_Generated by cngx_`
            }});
"""
        return yaml

    @staticmethod
    def save(
        output_path: str = ".github/workflows/cngx-gate.yml",
        **kwargs,
    ) -> str:
        """Generate and save GitHub Action workflow."""
        from pathlib import Path

        yaml_content = GitHubActionGenerator.generate(**kwargs)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(yaml_content, encoding="utf-8")
        return str(path)
