"""GitHub Action workflow generator for offline agent gating."""

from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger("cngx.enforcement.github_action")


class GitHubActionGenerator:
    """Generate GitHub Action workflow YAML for cngx offline gates."""

    @staticmethod
    def generate(
        python_version: str = "3.11",
        model: str = "agent-output",
        provider: str = "mock",
        contract_path: str = "examples/contracts/",
        api_key_secret: str = "GOOGLE_API_KEY",
        drift_threshold: float = 0.3,
        accuracy_threshold: float = 0.8,
        stability_threshold: float = 0.7,
        run_benchmark: bool = False,
        run_robustness: bool = False,
        run_consensus: bool = False,
        on_push: bool = True,
        on_pull_request: bool = True,
        branches: list[str] | None = None,
        additional_env: dict[str, str] | None = None,
        policy_file: str = "examples/contracts/coding_agent_verification.yaml",
        output_file: str = "agent_output.txt",
        evidence_file: str = "",
        cngx_version: str = "0.1.7",
    ) -> str:
        """Generate a workflow that gates agent output offline (no API keys).

        Legacy kwargs (provider, run_benchmark, etc.) are accepted for API
        compatibility but ignored: deferred SaaS commands are not generated.
        """
        _ = (
            model,
            provider,
            contract_path,
            api_key_secret,
            drift_threshold,
            accuracy_threshold,
            stability_threshold,
            run_benchmark,
            run_robustness,
            run_consensus,
            additional_env,
        )
        branches = branches or ["main"]
        branch_list = "\n".join(f"      - {b}" for b in branches)

        triggers: list[str] = []
        if on_push:
            triggers.append(f"  push:\n    branches:\n{branch_list}")
        if on_pull_request:
            triggers.append(f"  pull_request:\n    branches:\n{branch_list}")
        triggers.append("  workflow_dispatch:")
        on_block = "\n".join(triggers)

        evidence_input = ""
        if evidence_file:
            evidence_input = f"\n          evidence-file: {evidence_file}"

        return f"""# Generated by cngx. Offline agent gate (no provider API keys).
# https://github.com/aadi-joshi/cngx

name: cngx agent gate

on:
{on_block}

permissions:
  contents: read

jobs:
  gate:
    name: Gate agent output
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: cngx check
        uses: aadi-joshi/cngx@v{cngx_version}
        with:
          policy: {policy_file}
          output-file: {output_file}
          python-version: "{python_version}"
          cngx-version: "{cngx_version}"{evidence_input}
"""

    @staticmethod
    def save(
        output_path: str = ".github/workflows/cngx-gate.yml",
        **kwargs,
    ) -> str:
        """Generate and save GitHub Action workflow."""
        from pathlib import Path

        yaml_content = GitHubActionGenerator.generate(**kwargs)
        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(yaml_content, encoding="utf-8")
        return str(path)
